### ISSUE TITLE
Podspec seems a bit broken

### ISSUE THREAD

**Issue by hjaltij** [jondanao/TheSidebarController#2]
After basic pod install and importing <TheSidebarController/TheSidebarController.h>

The project does not build:

../Pods/Headers/TheSidebarController/TheSidebarController.h:26:9: 'SidebarAnimation.h' file not found

**Comment by mahmuzicamel** [comment]
Still experiencing the same issue

**Comment by siddhinho** [comment]
I have the same problem. 
Whats solution ?

**Comment by mahmuzicamel** [comment]
Sorry to say this here but I've used another library.
https://github.com/pkluz/PKRevealController

**Comment by Dellybro** [comment]
I still have that issue

**Comment by royherma** [comment]
Still experiencing this issue - any ideas @jondanao ? (new project xcode 7.3 / objc)
